spring.application.name=admin-cafe

server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://192.168.178.239:5432/wehr
spring.datasource.username=wehr
spring.datasource.password=bizwebwehr123$

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

app.cors.allowed-origins=https://admin-cafe-front.onrender.com/